### ISSUE TITLE
Other `ld` implementations

### ISSUE THREAD

**Issue by Artoria2e5** [jacksonp/ManKier-extra#10]
* `ld.gold(1)` is the other linker in binutils. It's ELF-only and faster.
* `lld(1)` is a linker from LLVM. It works with many targets and is always faster.

I don't know whether it's a Fedora thing or just some packages not installed, but it's weird to see `llc(1)` available but not `lld(1)` and vice versa.

**Comment by jacksonp** [comment]
Added:
- https://www.mankier.com/1/ld.gold
- https://www.mankier.com/1/ld.lld
