### ISSUE TITLE
Open-sourcing ManKier?

### ISSUE THREAD

**Issue by sebastiancarlos** [jacksonp/ManKier-extra#15]
Hey, first of all I just wanted to say that your work on ManKier is great. It’s in may respects the coolest online thing for man pages that I’ve ever seen. I’m also into hacking around man pages and I have some ideas, mostly about troff handling, that seem to align with what you’re doing. I know this might be a big ask, but how about making ManKier, or some bits of it, open-source? I would definitely want to contribute upstream any improvement that I make that might provide mutual benefit. And I don't mind php, that stuff runs the world.

Cheers mate. You’re doing great. Keep up the good work.

**Comment by jacksonp** [comment]
Hi, thanks for the kind words! I can't commit to making bits open-source in the immediate future, too many other time commitments. If I do in future it will be in another repo, and will post an update and link here.

**Comment by jacksonp** [comment]
See: https://github.com/jacksonp/manner (Converts troff man pages to semantic HTML).

**Comment by sebastiancarlos** [comment]
Looks great! I'll give it a try. Thanks for sharing.
