### ISSUE TITLE
Man pages from other distributions?

### ISSUE THREAD

**Issue by claes** [jacksonp/ManKier-extra#4]
Some commands are distribution-specific. I was looking to contribute the man pages of the wicked networking framework (OpenSUSE) that provides ifup(8) on that distribution. But that would collide with what is present in Mankier from Fedora. Is there a way to work around that?

**Comment by jacksonp** [comment]
Thanks for looking into that. Some packages use extensions, e.g.: https://www.mankier.com/package/openssl - could use .5wicked, .8wicked... extensions?

**Comment by claes** [comment]
Yes that might work. I will look into it.

**Comment by jacksonp** [comment]
Have added instructions in the README for name conflicts.

Some of the wicked man pages are available here by the way: https://www.mankier.com/package/wicked
